# Generated by Django 3.1.5 on 2021-01-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Доска', 'verbose_name_plural': 'Доски'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.AlterModelOptions(
            name='checklist',
            options={'verbose_name': 'Чек-лист', 'verbose_name_plural': 'Чек-листы'},
        ),
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'verbose_name': 'Задача чек-листа', 'verbose_name_plural': 'Задачи чек-листов'},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'verbose_name': 'Список', 'verbose_name_plural': 'Списки'},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'verbose_name': 'Метка', 'verbose_name_plural': 'Метки'},
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
