# Generated by Django 3.1.5 on 2021-02-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20210207_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Позиция в списке'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Позиция на картоке'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Позиция в чек-листе'),
        ),
        migrations.AlterField(
            model_name='list',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Позиция на доске'),
        ),
    ]
